export const CareersList = [
  {
    id: "country-head-sales",
    title: "Country Head - Sales",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dbUEtUM3",
  },
  {
    id: "head-m-a",
    title: "Head - M&A",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dn9t_K7A",
  },
  {
    id: "head-hr",
    title: "Head HR",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dZHafn-R",
  },
  {
    id: "head-fundraising-officer",
    title: "Head Fundraising Officer",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/ddwgnsqY",
  },
  {
    id: "head-of-products",
    title: "Head of Products",
    location: "Remote",
    type: "Full-time/Part-time",
    href: " https://lnkd.in/drSGxjma",
  },
  {
    id: "product-designer-lead",
    title: "Product Designer Lead",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dv8QHPCD",
  },
  {
    id: "full-stack-hands-on-engineering-manager-lead",
    title: "Full Stack Hands-on Engineering Manager/Lead",
    location: "Remote",
    type: "Full-time/Part-time",
    href: " https://lnkd.in/dVhrhUrq",
  },
  {
    id: "product-manager",
    title: "Product Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dNtJTWGr",
  },
  {
    id: "project-manager-1",
    title: "Project Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dAaJPx6A",
  },
  {
    id: "fundraising-manager",
    title: "Fundraising Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dXW2zDed",
  },
  {
    id: "customer-success-and-client-onboarding-manager",
    title: "Customer Success & Client Onboarding Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dPzaaZmm",
  },
  {
    id: "m-a-specialist-manager",
    title: "M&A Specialist - Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dWTkFPPw",
  },
  {
    id: "hr-manager",
    title: "HR Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dMGiKUjq",
  },
  {
    id: "executive-assistant-to-founder-and-ceo",
    title: "Executive Assistant to Founder & CEO",
    location: "Tampa, FL",
    type: "Part-time",
    href: "https://lnkd.in/dYVs6Uwa",
  },
  {
    id: "chief-operating-officer",
    title: "Chief Operating Officer",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dcaw_zdp",
  },
  {
    id: "chief-technology-officer",
    title: "Chief Technology Officer (CTO)",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "https://lnkd.in/dmshACNY",
  },
  {
    id: "sales-intern",
    title: "Sales Intern",
    location: "Remote",
    type: "Internship",
    href: "https://lnkd.in/dXBHFjyA",
  },
  {
    id: "hr-intern",
    title: "HR Intern",
    location: "Remote",
    type: "Internship",
    href: "https://lnkd.in/dsWXVteF",
  },
  {
    id: "product-intern",
    title: "Product Intern",
    location: "Remote",
    type: "Internship",
    href: "https://lnkd.in/dQE7QMDM",
  },
  {
    id: "full-stack-developer-intern",
    title: "Full Stack Developer Intern",
    location: "Remote",
    type: "Internship",
    href: "https://lnkd.in/dPH3mx4x",
  },
];
