import { Briefcase } from "lucide-react";

const roleList = [
  {
    name: "Chief Sales Officer",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/chief-sales-officer",
    icon: Briefcase,
    tags: ["Sales"],
  },
  {
    name: "Chief Operating Officer",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/chief-operations-officer",
    icon: Briefcase,
    tags: ["General"],
  },
  {
    name: "Chief Technology Officer",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/chief-technology-officer",
    icon: Briefcase,
    tags: ["Tech"],
  },
  {
    name: "Head of Sales - Country",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/head-sales-country",
    icon: Briefcase,
    tags: ["Sales"],
  },
  {
    name: "Head of Human Resources",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/head-human-resources",
    icon: Briefcase,
    tags: ["HR"],
  },
  {
    name: "Head of Products",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/head-products",
    icon: Briefcase,
    tags: ["Product"],
  },
  {
    name: "Head of M&A",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/head-mergers-acquisitions",
    icon: Briefcase,
    tags: ["General"],
  },
  {
    name: "Head of Fundraising",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/head-fundraising",
    icon: Briefcase,
    tags: ["Fundraising"],
  },
  {
    name: "Customer Success Manager",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/manager-operations-customer-success",
    icon: Briefcase,
    tags: ["Management"],
  },
  {
    name: "Full Stack Engineering Manager",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/manager-technology-fullstack-engineer",
    icon: Briefcase,
    tags: ["Management", "Tech"],
  },
  {
    name: "Human Resources Manager",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/manager-human-resources",
    icon: Briefcase,
    tags: ["Management", "HR"],
  },
  {
    name: "Product Manager",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/manager-product",
    icon: Briefcase,
    tags: ["Management", "Product"],
  },
  {
    name: "M&A Specialist Manager",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/manager-mergers-acquisitions-specialist",
    icon: Briefcase,
    tags: ["Management"],
  },
  {
    name: "Fundraising Manager",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/manager-fundraising",
    icon: Briefcase,
    tags: ["Management", "Fundraising"],
  },
  {
    name: "Project Manager",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/manager-project",
    icon: Briefcase,
    tags: ["Management", "Project"],
  },
  {
    name: "Lead Product Designer",
    provider: "Remote",
    description: "Full-time/Part-time",
    link: "/careers/lead-product-designer",
    icon: Briefcase,
    tags: ["Product", "Design"],
  },
  {
    name: "Sales and Marketing Intern",
    provider: "Remote",
    description: "Internship",
    link: "/careers/intern-sales-marketing",
    icon: Briefcase,
    tags: ["Internship", "Sales", "Marketing"],
  },
  {
    name: "HR Intern",
    provider: "Remote",
    description: "Internship",
    link: "/careers/intern-human-resources",
    icon: Briefcase,
    tags: ["Internship", "HR"],
  },
  {
    name: "Product Marketing Intern",
    provider: "Remote",
    description: "Internship",
    link: "/careers/intern-product-marketing",
    icon: Briefcase,
    tags: ["Internship", "Product", "Marketing"],
  },
  {
    name: "Full Stack Developer Intern",
    provider: "Remote",
    description: "Internship",
    link: "/careers/intern-technology-fullstack-developer",
    icon: Briefcase,
    tags: ["Internship", "Tech"],
  },
  {
    name: "Executive Assistant to Founder",
    provider: "Tampa, FL",
    description: "Part-time",
    link: "/careers/assistant-operations-founder",
    icon: Briefcase,
    tags: ["General"],
  },
];

export { roleList };
