const jobList = [
  {
    id: "board-advisor-technology",
    title: "Board Advisor – Technology",
    location: "Remote",
    type: "Part-Time/Advisory",
    href: "careers/board-advisor-technology",
  },
  {
    id: "board-advisor-finance",
    title: "Board Advisor – Finance",
    location: "Remote",
    type: "Part-Time/Advisory",
    href: "careers/board-advisor-finance",
  },
  {
    id: "board-advisor-sales-growth",
    title: "Board Advisor – Sales & Growth",
    location: "Remote",
    type: "Part-Time/Advisory",
    href: "careers/board-advisor-sales-growth",
  },
  {
    id: "board-advisor-legal",
    title: "Board Advisor – Legal",
    location: "Remote",
    type: "Part-Time/Advisory",
    href: "careers/board-advisor-legal",
  },
  {
    id: "chief-sales-officer",
    title: "Chief Sales Officer",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/chief-sales-officer",
  },
  {
    id: "chief-operations-officer",
    title: "Chief Operating Officer",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/chief-operations-officer",
  },
  {
    id: "chief-technology-officer",
    title: "Chief Technology Officer",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/chief-technology-officer",
  },
  {
    id: "head-sales-country",
    title: "Head of Sales - Country",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/head-sales-country",
  },
  {
    id: "head-human-resources",
    title: "Head of Human Resources",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/head-human-resources",
  },
  {
    id: "head-products",
    title: "Head of Products",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/head-products",
  },
  {
    id: "head-mergers-acquisitions",
    title: "Head of M&A",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/head-mergers-acquisitions",
  },
  {
    id: "head-fundraising",
    title: "Head of Fundraising",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/head-fundraising",
  },
  {
    id: "manager-accounts-payroll",
    title: "Accounts and Payroll Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "careers/manager-accounts-payroll",
  },
  {
    id: "manager-operations-customer-success",
    title: "Customer Success Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/manager-operations-customer-success",
  },
  {
    id: "manager-technology-fullstack-engineer",
    title: "Full Stack Engineering Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/manager-technology-fullstack-engineer",
  },
  {
    id: "manager-human-resources",
    title: "Human Resources Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/manager-human-resources",
  },
  {
    id: "manager-product",
    title: "Product Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/manager-product",
  },
  {
    id: "manager-mergers-acquisitions-specialist",
    title: "M&A Specialist Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/manager-mergers-acquisitions-specialist",
  },
  {
    id: "manager-fundraising",
    title: "Fundraising Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/manager-fundraising",
  },
  {
    id: "manager-project",
    title: "Project Manager",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/manager-project",
  },
  {
    id: "lead-product-designer",
    title: "Lead Product Designer",
    location: "Remote",
    type: "Full-time/Part-time",
    href: "/careers/lead-product-designer",
  },
  {
    id: "intern-sales-marketing",
    title: "Sales and Marketing Intern",
    location: "Remote",
    type: "Internship",
    href: "/careers/intern-sales-marketing",
  },
  {
    id: "intern-human-resources",
    title: "HR Intern",
    location: "Remote",
    type: "Internship",
    href: "/careers/intern-human-resources",
  },
  {
    id: "intern-product-marketing",
    title: "Product Marketing Intern",
    location: "Remote",
    type: "Internship",
    href: "/careers/intern-product-marketing",
  },
  {
    id: "intern-technology-fullstack-developer",
    title: "Full Stack Developer Intern",
    location: "Remote",
    type: "Internship",
    href: "/careers/intern-technology-fullstack-developer",
  },
  {
    id: "assistant-operations-founder",
    title: "Executive Assistant to Founder",
    location: "Tampa, FL",
    type: "Part-time",
    href: "/careers/assistant-operations-founder",
  },
];

export { jobList };
