const jobListData = [
  {
    id: "board-advisor-sales-growth",
    title: "Board Advisor – Sales & Growth",
    department: "Sales & Marketing",
    level: "Board",
    href: "/careers/board-advisor-sales-growth",
    featured: true,
  },
  {
    id: "board-advisor-technology",
    title: "Board Advisor – Technology",
    department: "Technology",
    level: "Board",
    href: "/careers/board-advisor-technology",
  },
  {
    id: "board-advisor-finance",
    title: "Board Advisor – Finance",
    department: "Finance",
    level: "Board",
    href: "/careers/board-advisor-finance",
  },
  {
    id: "board-advisor-legal",
    title: "Board Advisor – Legal",
    department: "Legal & Strategy",
    level: "Board",
    href: "/careers/board-advisor-legal",
  },
  {
    id: "svp-technology-ai",
    title: "SVP of Technology – Artificial Intelligence",
    department: "Technology",
    level: "VP",
    href: "/careers/svp-technology-ai",
  },
  {
    id: "chief-financial-officer",
    title: "Chief Financial Officer",
    department: "Finance",
    level: "Chief",
    href: "/careers/chief-financial-officer",
  },
  {
    id: "chief-sales-officer",
    title: "Chief Sales Officer",
    department: "Sales & Marketing",
    level: "Chief",
    href: "/careers/chief-sales-officer",
  },
  {
    id: "chief-operations-officer",
    title: "Chief Operating Officer",
    department: "Operations",
    level: "Chief",
    href: "/careers/chief-operations-officer",
  },
  {
    id: "chief-technology-officer",
    title: "Chief Technology Officer",
    department: "Technology",
    level: "Chief",
    href: "/careers/chief-technology-officer",
  },
  {
    id: "vp-technology",
    title: "Vice President of Technology",
    department: "Technology",
    level: "VP",
    href: "/careers/vp-technology",
  },
  {
    id: "architect-ai-solutions",
    title: "AI Solution Architect",
    department: "Technology",
    level: "Engineer",
    href: "/careers/architect-ai-solutions",
  },
  {
    id: "head-sales-country",
    title: "Head of Sales - Country",
    department: "Sales & Marketing",
    level: "Head",
    href: "/careers/head-sales-country",
  },
  {
    id: "head-human-resources",
    title: "Head of Human Resources",
    department: "People Ops",
    level: "Head",
    href: "/careers/head-human-resources",
  },
  {
    id: "head-products",
    title: "Head of Products",
    department: "Product & Design",
    level: "Head",
    href: "/careers/head-products",
  },
  {
    id: "head-mergers-acquisitions",
    title: "Head of M&A",
    department: "Legal & Strategy",
    level: "Head",
    href: "/careers/head-mergers-acquisitions",
  },
  {
    id: "head-fundraising",
    title: "Head of Fundraising",
    department: "Finance",
    level: "Head",
    href: "/careers/head-fundraising",
  },
  {
    id: "manager-human-resources",
    title: "Human Resources Manager",
    department: "People Ops",
    level: "Manager",
    href: "/careers/manager-human-resources",
  },
  {
    id: "manager-product",
    title: "Product Manager",
    department: "Product & Design",
    level: "Manager",
    href: "/careers/manager-product",
  },
  {
    id: "manager-mergers-acquisitions-specialist",
    title: "M&A Specialist Manager",
    department: "Legal & Strategy",
    level: "Manager",
    href: "/careers/manager-mergers-acquisitions-specialist",
  },
  {
    id: "manager-fundraising",
    title: "Fundraising Manager",
    department: "Finance",
    level: "Manager",
    href: "/careers/manager-fundraising",
  },
  {
    id: "manager-operations-customer-success",
    title: "Customer Success Manager",
    department: "Operations",
    level: "Manager",
    href: "/careers/manager-operations-customer-success",
  },
  {
    id: "manager-technology-fullstack-engineer",
    title: "Full Stack Engineering Manager",
    department: "Technology",
    level: "Manager",
    href: "/careers/manager-technology-fullstack-engineer",
  },
  {
    id: "manager-project",
    title: "Project Manager",
    department: "Operations",
    level: "Manager",
    href: "/careers/manager-project",
  },
  {
    id: "manager-accounts-payroll",
    title: "Accounts and Payroll Manager",
    department: "Finance",
    level: "Manager",
    href: "/careers/manager-accounts-payroll",
  },
  {
    id: "engineer-machine-learning",
    title: "ML Engineer",
    department: "Technology",
    level: "Engineer",
    href: "/careers/engineer-machine-learning",
  },
  {
    id: "engineer-software",
    title: "Software Engineer",
    department: "Technology",
    level: "Engineer",
    href: "/careers/engineer-software",
  },
  {
    id: "marketer-performance",
    title: "Performance Marketer",
    department: "Sales & Marketing",
    level: "Engineer",
    href: "/careers/marketer-performance",
  },
  {
    id: "designer-graphic",
    title: "Graphic Designer",
    department: "Product & Design",
    level: "Engineer",
    href: "/careers/designer-graphic",
  },
  {
    id: "designer-uiux",
    title: "UI/UX Designer",
    department: "Product & Design",
    level: "Engineer",
    href: "/careers/designer-uiux",
  },
  {
    id: "lead-product-designer",
    title: "Lead Product Designer",
    department: "Product & Design",
    level: "Lead",
    href: "/careers/lead-product-designer",
  },
  {
    id: "lead-social-media-strategy",
    title: "Lead Social Media Strategy",
    department: "Product & Design",
    level: "Lead",
    href: "/careers/lead-social-media-strategy",
  },
  {
    id: "intern-sales-marketing",
    title: "Sales and Marketing Intern",
    department: "Sales & Marketing",
    level: "Intern",
    href: "/careers/intern-sales-marketing",
  },
  {
    id: "intern-human-resources",
    title: "HR Intern",
    department: "People Ops",
    level: "Intern",
    href: "/careers/intern-human-resources",
  },
  {
    id: "intern-product-marketing",
    title: "Product Marketing Intern",
    department: "Sales & Marketing",
    level: "Intern",
    href: "/careers/intern-product-marketing",
  },
  {
    id: "intern-technology-fullstack-developer",
    title: "Full Stack Developer Intern",
    department: "Technology",
    level: "Engineer",
    href: "/careers/intern-technology-fullstack-developer",
  },
  {
    id: "assistant-operations-founder",
    title: "Executive Assistant – Founder",
    department: "Operations",
    level: "Assistant",
    href: "/careers/assistant-operations-founder",
  },
];

export default jobListData;
